#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <windowsx.h>
#include <commdlg.h>
#include <fstream>
#include <sstream>
#include <vector>
#include <string>
#include <cmath>
#include <algorithm>
#include <cstdio>
#include <cstring>

struct Obj { std::string name; int type=0; float x=0,y=0,z=0,rx=0,ry=0,rz=0,sx=1,sy=1,sz=1; int color=0; };
static std::vector<Obj> scene; static int selected=-1; static bool hub=true, playing=false, dirty=false;
static HWND mainWnd, viewport, hierarchy, statusWnd, nameEdit, xEdit,yEdit,zEdit,rxEdit,ryEdit,rzEdit,sxEdit,syEdit,szEdit;
static std::string projectFile; static float yaw=-0.65f,pitch=0.35f,distance=12.f,panX=0,panY=0; static POINT dragStart{}; static bool orbiting=false,panning=false;
static constexpr int ID_NEW=101,ID_OPEN=102,ID_RECENT=103,ID_SETTINGS=104,ID_ADD_CUBE=105,ID_ADD_SPHERE=106,ID_ADD_PLANE=107,ID_DELETE=108,ID_DUP=109,ID_SAVE=110,ID_LOAD=111,ID_PLAY=112,ID_STOP=113,ID_HUB=114,ID_APPLY=115,ID_HIER=116,ID_FOCUS=117;
static void showEditor(); static void showHub();
static void status(const std::string&s){if(statusWnd)SetWindowTextA(statusWnd,s.c_str());}
static void setFloat(HWND h,float v){char b[48];sprintf_s(b,"%.3f",v);SetWindowTextA(h,b);}
static float getFloat(HWND h,float old){char b[64];GetWindowTextA(h,b,64);char*e=nullptr;float v=strtof(b,&e);return e!=b?v:old;}
static void refresh(){if(!hierarchy)return;SendMessageA(hierarchy,LB_RESETCONTENT,0,0);for(auto&o:scene){std::string s=(o.type==1?"Sphere  ":o.type==2?"Plane   ":"Cube    ")+o.name;SendMessageA(hierarchy,LB_ADDSTRING,0,(LPARAM)s.c_str());}if(selected>=0&&(size_t)selected<scene.size()){auto&o=scene[selected];SendMessageA(hierarchy,LB_SETCURSEL,selected,0);SetWindowTextA(nameEdit,o.name.c_str());setFloat(xEdit,o.x);setFloat(yEdit,o.y);setFloat(zEdit,o.z);setFloat(rxEdit,o.rx);setFloat(ryEdit,o.ry);setFloat(rzEdit,o.rz);setFloat(sxEdit,o.sx);setFloat(syEdit,o.sy);setFloat(szEdit,o.sz);}InvalidateRect(viewport,nullptr,FALSE);}
static void saveScene(){if(projectFile.empty()){status("No project selected");return;}std::ofstream f(projectFile,std::ios::trunc);if(!f){status("ERROR: could not save project");return;}f<<"TinyAI 2\n";for(auto&o:scene)f<<"object \""<<o.name<<"\" "<<o.type<<' '<<o.x<<' '<<o.y<<' '<<o.z<<' '<<o.rx<<' '<<o.ry<<' '<<o.rz<<' '<<o.sx<<' '<<o.sy<<' '<<o.sz<<' '<<o.color<<"\n";dirty=false;status("Saved: "+projectFile);}
static bool readQuoted(std::istream&in,std::string&out){in>>std::ws;if(in.peek()!='\"'){in>>out;return bool(in);}in.get();std::getline(in,out,'\"');return bool(in);}
static void loadScene(){if(projectFile.empty())return;std::ifstream f(projectFile);if(!f){status("ERROR: could not open project");return;}std::string h;f>>h;scene.clear();std::string t;while(f>>t){if(t!="object")break;Obj o;if(!readQuoted(f,o.name))break;f>>o.type>>o.x>>o.y>>o.z>>o.rx>>o.ry>>o.rz>>o.sx>>o.sy>>o.sz>>o.color;if(f)scene.push_back(o);}if(scene.empty())scene.push_back({"Cube",0,0,0,0,0,0,1,1,1,0});selected=scene.empty()?-1:0;dirty=false;refresh();status("Loaded: "+projectFile);}
static void newProject(){char file[MAX_PATH]="MyGame.tinyproj";OPENFILENAMEA o{};o.lStructSize=sizeof(o);o.hwndOwner=mainWnd;o.lpstrFile=file;o.nMaxFile=MAX_PATH;o.lpstrFilter="Tiny AI Project\0*.tinyproj\0All Files\0*.*\0\0";o.Flags=OFN_OVERWRITEPROMPT;if(!GetSaveFileNameA(&o))return;projectFile=file;scene={{"Main Camera",0,0,0,0,0,0,1,1,1,0},{"Cube",0,0,0,0,0,0,1,1,1,0}};selected=1;dirty=true;saveScene();showEditor();}
static void openProject(){char file[MAX_PATH]={};OPENFILENAMEA o{};o.lStructSize=sizeof(o);o.hwndOwner=mainWnd;o.lpstrFile=file;o.nMaxFile=MAX_PATH;o.lpstrFilter="Tiny AI Project\0*.tinyproj\0All Files\0*.*\0\0";o.Flags=OFN_FILEMUSTEXIST;if(!GetOpenFileNameA(&o))return;projectFile=file;loadScene();showEditor();}
static void addObj(int type){const char*base=type==1?"Sphere":type==2?"Plane":"Cube";int n=1;for(auto&o:scene)if(o.name.rfind(base,0)==0)n++;Obj o;o.name=std::string(base)+std::to_string(n);o.type=type;o.x=(float)((int)scene.size()%5-2)*2.f;o.z=(float)((int)scene.size()/5)*2.f;scene.push_back(o);selected=(int)scene.size()-1;dirty=true;refresh();status(std::string(base)+" added");}
static void deleteObj(){if(selected<0||selected>=(int)scene.size())return;if(scene[selected].name=="Main Camera"){status("Camera cannot be deleted");return;}scene.erase(scene.begin()+selected);selected=scene.empty()?-1:std::min(selected,(int)scene.size()-1);dirty=true;refresh();status("Object deleted");}
static void duplicateObj(){if(selected<0||selected>=(int)scene.size())return;Obj o=scene[selected];o.name+=" Copy";o.x+=1.f;o.z+=1.f;scene.push_back(o);selected=(int)scene.size()-1;dirty=true;refresh();status("Object duplicated");}
static void apply(){if(selected<0||selected>=(int)scene.size())return;auto&o=scene[selected];char n[128];GetWindowTextA(nameEdit,n,128);if(n[0])o.name=n;o.x=getFloat(xEdit,o.x);o.y=getFloat(yEdit,o.y);o.z=getFloat(zEdit,o.z);o.rx=getFloat(rxEdit,o.rx);o.ry=getFloat(ryEdit,o.ry);o.rz=getFloat(rzEdit,o.rz);o.sx=getFloat(sxEdit,o.sx);o.sy=getFloat(syEdit,o.sy);o.sz=getFloat(szEdit,o.sz);dirty=true;refresh();status("Inspector applied");}
static POINT project(float x,float y,float z,RECT&r){float cy=cosf(yaw),sy=sinf(yaw),cp=cosf(pitch),sp=sinf(pitch);x-=panX;y-=panY;float X=x*cy-z*sy,Z=x*sy+z*cy;float Y=y*cp-Z*sp;Z=y*sp+Z*cp+distance;float f=0.9f;return {(LONG)(r.right/2+X*f*r.bottom/Z),(LONG)(r.bottom/2-Y*f*r.bottom/Z)};}
static void lineCube(HDC dc,const Obj&o,RECT&r,bool sel){float rx=o.rx*0.0174533f,ry=o.ry*0.0174533f,rz=o.rz*0.0174533f;float v[8][3]={{-1,-1,-1},{1,-1,-1},{1,1,-1},{-1,1,-1},{-1,-1,1},{1,-1,1},{1,1,1},{-1,1,1}};POINT p[8];for(int i=0;i<8;i++){float x=v[i][0]*o.sx,y=v[i][1]*o.sy,z=v[i][2]*o.sz;float cx=cosf(rx),sx=sin(rx),cy=cosf(ry),sy=sin(ry),cz=cosf(rz),sz=sin(rz);float y1=y*cx-z*sx,z1=y*sx+z*cx;float x2=x*cy-z1*sy,z2=x*sy+z1*cy;float x3=x2*cz-y1*sz,y3=x2*sz+y1*cz;p[i]=project(x3+o.x,y3+o.y,z2+o.z,r);}int e[][2]={{0,1},{1,2},{2,3},{3,0},{4,5},{5,6},{6,7},{7,4},{0,4},{1,5},{2,6},{3,7}};HPEN pen=CreatePen(PS_SOLID,sel?3:1,sel?RGB(255,180,60):RGB(130,160,190));HGDIOBJ old=SelectObject(dc,pen);for(auto&a:e){MoveToEx(dc,p[a[0]].x,p[a[0]].y,nullptr);LineTo(dc,p[a[1]].x,p[a[1]].y);}SelectObject(dc,old);DeleteObject(pen);}
static void grid(HDC dc,RECT&r){HPEN p=CreatePen(PS_SOLID,1,RGB(48,53,64));HGDIOBJ old=SelectObject(dc,p);for(int i=-12;i<=12;i++){POINT a=project((float)i,0,-12,r),b=project((float)i,0,12,r);MoveToEx(dc,a.x,a.y,nullptr);LineTo(dc,b.x,b.y);a=project(-12,0,(float)i,r);b=project(12,0,(float)i,r);MoveToEx(dc,a.x,a.y,nullptr);LineTo(dc,b.x,b.y);}SelectObject(dc,old);DeleteObject(p);}
static int hitTest(int mx,int my,RECT&r){int best=-1;float bd=55;for(int i=0;i<(int)scene.size();i++){if(scene[i].name=="Main Camera")continue;POINT p=project(scene[i].x,scene[i].y,scene[i].z,r);float d=hypotf(float(p.x-mx),float(p.y-my));float rad=30.f*std::max({scene[i].sx,scene[i].sy,scene[i].sz});if(d<bd+rad){bd=d+rad;best=i;}}return best;}
static LRESULT CALLBACK viewportProc(HWND h,UINT m,WPARAM w,LPARAM l){if(m==WM_LBUTTONDOWN){SetCapture(h);dragStart={GET_X_LPARAM(l),GET_Y_LPARAM(l)};if(w&MK_SHIFT)panning=true;else{RECT r;GetClientRect(h,&r);int hit=hitTest(dragStart.x,dragStart.y,r);if(hit>=0){selected=hit;refresh();}else selected=-1;}return 0;}if(m==WM_LBUTTONUP){ReleaseCapture();panning=false;return 0;}if(m==WM_RBUTTONDOWN){SetCapture(h);dragStart={GET_X_LPARAM(l),GET_Y_LPARAM(l)};orbiting=true;return 0;}if(m==WM_RBUTTONUP){ReleaseCapture();orbiting=false;return 0;}if(m==WM_MOUSEMOVE){int x=GET_X_LPARAM(l),y=GET_Y_LPARAM(l);if(orbiting){yaw+=(x-dragStart.x)*0.008f;pitch+=(y-dragStart.y)*0.008f;pitch=std::clamp(pitch,-1.45f,1.45f);dragStart={x,y};InvalidateRect(h,nullptr,FALSE);}else if(panning){panX-=(x-dragStart.x)*0.01f;panY+=(y-dragStart.y)*0.01f;dragStart={x,y};InvalidateRect(h,nullptr,FALSE);}return 0;}if(m==WM_MOUSEWHEEL){distance*=powf(0.9f,(float)GET_WHEEL_DELTA_WPARAM(w)/120.f);distance=std::clamp(distance,2.f,100.f);InvalidateRect(h,nullptr,FALSE);return 0;}if(m==WM_PAINT){PAINTSTRUCT ps;HDC dc=BeginPaint(h,&ps);RECT r;GetClientRect(h,&r);HBRUSH b=CreateSolidBrush(RGB(27,30,37));FillRect(dc,&r,b);DeleteObject(b);grid(dc,r);for(auto&o:scene)if(o.name!="Main Camera")lineCube(dc,o,r,&o==&scene[selected]);SetBkMode(dc,TRANSPARENT);SetTextColor(dc,RGB(170,180,195));TextOutA(dc,12,10,"SCENE",5);TextOutA(dc,12,30,"RMB Orbit   Shift+LMB Pan   Wheel Zoom",34);EndPaint(h,&ps);return 0;}return DefWindowProcA(h,m,w,l);}
static void modeButton(int id,bool visible){ShowWindow(GetDlgItem(mainWnd,id),visible?SW_SHOW:SW_HIDE);}
static void showHub(){hub=true;playing=false;for(int id:{ID_NEW,ID_OPEN,ID_RECENT,ID_SETTINGS})modeButton(id,true);for(int id:{ID_ADD_CUBE,ID_ADD_SPHERE,ID_ADD_PLANE,ID_DELETE,ID_DUP,ID_SAVE,ID_LOAD,ID_PLAY,ID_STOP,ID_HUB,ID_APPLY,ID_FOCUS})modeButton(id,false);ShowWindow(viewport,SW_HIDE);ShowWindow(hierarchy,SW_HIDE);for(HWND h:{nameEdit,xEdit,yEdit,zEdit,rxEdit,ryEdit,rzEdit,sxEdit,syEdit,szEdit})ShowWindow(h,SW_HIDE);status("Tiny AI Game Engine Hub");InvalidateRect(mainWnd,nullptr,TRUE);}
static void showEditor(){hub=false;for(int id:{ID_NEW,ID_OPEN,ID_RECENT,ID_SETTINGS})modeButton(id,false);for(int id:{ID_ADD_CUBE,ID_ADD_SPHERE,ID_ADD_PLANE,ID_DELETE,ID_DUP,ID_SAVE,ID_LOAD,ID_PLAY,ID_STOP,ID_HUB,ID_APPLY,ID_FOCUS})modeButton(id,true);ShowWindow(viewport,SW_SHOW);ShowWindow(hierarchy,SW_SHOW);for(HWND h:{nameEdit,xEdit,yEdit,zEdit,rxEdit,ryEdit,rzEdit,sxEdit,syEdit,szEdit})ShowWindow(h,SW_SHOW);refresh();}
static void button(const char*t,int id,int x,int y,int w,int h){CreateWindowA("BUTTON",t,WS_CHILD|WS_VISIBLE,x,y,w,h,mainWnd,(HMENU)id,GetModuleHandleA(nullptr),nullptr);}
static void label(const char*t,int x,int y,int w=60){CreateWindowA("STATIC",t,WS_CHILD|WS_VISIBLE,x,y,w,20,mainWnd,nullptr,GetModuleHandleA(nullptr),nullptr);}
static HWND edit(const char*t,int x,int y,int w=70){return CreateWindowA("EDIT",t,WS_CHILD|WS_BORDER|ES_AUTOHSCROLL,x,y,w,24,mainWnd,nullptr,GetModuleHandleA(nullptr),nullptr);}
static LRESULT CALLBACK wndProc(HWND h,UINT m,WPARAM w,LPARAM l){if(m==WM_COMMAND){int id=LOWORD(w);if(id==ID_HIER&&HIWORD(w)==LBN_SELCHANGE){selected=(int)SendMessageA(hierarchy,LB_GETCURSEL,0,0);refresh();return 0;}switch(id){case ID_NEW:newProject();break;case ID_OPEN:openProject();break;case ID_ADD_CUBE:addObj(0);break;case ID_ADD_SPHERE:addObj(1);break;case ID_ADD_PLANE:addObj(2);break;case ID_DELETE:deleteObj();break;case ID_DUP:duplicateObj();break;case ID_SAVE:saveScene();break;case ID_LOAD:loadScene();break;case ID_APPLY:apply();break;case ID_HUB:showHub();break;case ID_FOCUS:if(selected>=0){panX=scene[selected].x;panY=scene[selected].y;distance=8;}InvalidateRect(viewport,nullptr,FALSE);break;case ID_PLAY:playing=true;status("PLAY MODE: scene is running");break;case ID_STOP:playing=false;status("EDITOR MODE");break;case ID_RECENT:status("Recent project list will be persisted in a later release");break;case ID_SETTINGS:status("Editor settings will be persisted in a later release");break;}}if(m==WM_TIMER){if(playing){for(auto&o:scene)if(o.name!="Main Camera")o.ry+=0.7f;InvalidateRect(viewport,nullptr,FALSE);} }if(m==WM_KEYDOWN&&w==VK_DELETE){deleteObj();return 0;}if(m==WM_PAINT&&hub){PAINTSTRUCT ps;HDC dc=BeginPaint(h,&ps);RECT r;GetClientRect(h,&r);HBRUSH b=CreateSolidBrush(RGB(20,23,30));FillRect(dc,&r,b);DeleteObject(b);SetBkMode(dc,TRANSPARENT);SetTextColor(dc,RGB(235,238,245));HFONT f=CreateFontA(38,0,0,0,FW_BOLD,0,0,0,DEFAULT_CHARSET,0,0,0,0,"Segoe UI");HGDIOBJ old=SelectObject(dc,f);RECT t=r;t.top=55;DrawTextA(dc,"TINY AI GAME ENGINE",-1,&t,DT_CENTER|DT_TOP);SelectObject(dc,old);DeleteObject(f);SetTextColor(dc,RGB(145,155,170));t.top=108;DrawTextA(dc,"Create. Build. Play.",-1,&t,DT_CENTER|DT_TOP);EndPaint(h,&ps);return 0;}if(m==WM_DESTROY){PostQuitMessage(0);return 0;}return DefWindowProcA(h,m,w,l);}
int WINAPI WinMain(HINSTANCE hi,HINSTANCE,LPSTR,int){WNDCLASSA wc{};wc.hInstance=hi;wc.lpfnWndProc=wndProc;wc.lpszClassName="TinyAIEditor";wc.hCursor=LoadCursor(nullptr,IDC_ARROW);wc.hbrBackground=(HBRUSH)(COLOR_WINDOW+1);RegisterClassA(&wc);WNDCLASSA vc{};vc.hInstance=hi;vc.lpfnWndProc=viewportProc;vc.lpszClassName="TinyAIViewport";vc.hCursor=LoadCursor(nullptr,IDC_CROSS);RegisterClassA(&vc);mainWnd=CreateWindowA(wc.lpszClassName,"Tiny AI Game Engine",WS_OVERLAPPEDWINDOW|WS_VISIBLE,80,50,1250,780,nullptr,nullptr,hi,nullptr);
button("New Project",ID_NEW,20,155,180,42);button("Open Project",ID_OPEN,20,207,180,42);button("Recent Projects",ID_RECENT,20,259,180,42);button("Settings",ID_SETTINGS,20,311,180,42);
button("Cube",ID_ADD_CUBE,220,32,70,30);button("Sphere",ID_ADD_SPHERE,295,32,75,30);button("Plane",ID_ADD_PLANE,375,32,70,30);button("Delete",ID_DELETE,450,32,70,30);button("Duplicate",ID_DUP,525,32,80,30);button("Save",ID_SAVE,610,32,65,30);button("Load",ID_LOAD,680,32,65,30);button("Play",ID_PLAY,750,32,65,30);button("Stop",ID_STOP,820,32,65,30);button("Hub",ID_HUB,890,32,65,30);button("Focus",ID_FOCUS,960,32,65,30);button("Apply",ID_APPLY,1050,610,90,30);
viewport=CreateWindowA(vc.lpszClassName,"",WS_CHILD|WS_BORDER,220,70,700,650,mainWnd,nullptr,hi,nullptr);hierarchy=CreateWindowA("LISTBOX","",WS_CHILD|WS_BORDER|LBS_NOTIFY,940,70,270,300,mainWnd,(HMENU)ID_HIER,hi,nullptr);
label("Name",940,390,50);nameEdit=edit("",995,388,215);label("Position",940,425,70);xEdit=edit("0",940,448);yEdit=edit("0",1018,448);zEdit=edit("0",1096,448);label("Rotation",940,480,70);rxEdit=edit("0",940,503);ryEdit=edit("0",1018,503);rzEdit=edit("0",1096,503);label("Scale",940,535,60);sxEdit=edit("1",940,558);syEdit=edit("1",1018,558);szEdit=edit("1",1096,558);statusWnd=CreateWindowA("STATIC","",WS_CHILD|WS_VISIBLE,20,735,1180,24,mainWnd,nullptr,hi,nullptr);
scene={{"Main Camera",0,0,0,0,0,0,1,1,1,0},{"Cube",0,0,0,0,0,0,1,1,1,0}};selected=1;SetTimer(mainWnd,1,16,nullptr);showHub();MSG msg{};while(GetMessageA(&msg,nullptr,0,0)){TranslateMessage(&msg);DispatchMessageA(&msg);}return 0;}
