#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <windowsx.h>
#include <commdlg.h>
#include <fstream>
#include <string>
#include <vector>
#include <cmath>
#include <algorithm>
#include <cstdio>

struct Obj{std::string name;float x=0,y=0,z=0,rx=0,ry=0,rz=0,scale=1;};
static std::vector<Obj> scene; static int selected=-1; static bool hub=true; static float angle=0;
static HWND mainWnd,viewport,hierarchy,statusWnd,nameEdit,xEdit,yEdit,zEdit,scaleEdit;
static std::string projectFile;

enum{ID_NEW=101,ID_OPEN,ID_RECENT,ID_SETTINGS,ID_ADD,ID_DELETE,ID_SAVE,ID_LOAD,ID_BUILD,ID_PLAY,ID_HUB,ID_APPLY,ID_HIER};
static void showEditor(); static void showHub();
static void status(const std::string&s){if(statusWnd)SetWindowTextA(statusWnd,s.c_str());}
static void setFloat(HWND h,float v){char b[32];sprintf_s(b,"%.3f",v);SetWindowTextA(h,b);}
static float getFloat(HWND h,float old){char b[64];GetWindowTextA(h,b,64);char*e=nullptr;float v=strtof(b,&e);return e!=b?v:old;}
static void refresh(){if(!hierarchy)return;SendMessageA(hierarchy,LB_RESETCONTENT,0,0);for(auto&o:scene)SendMessageA(hierarchy,LB_ADDSTRING,0,(LPARAM)o.name.c_str());if(selected>=0)SendMessageA(hierarchy,LB_SETCURSEL,selected,0);if(selected>=0&&(size_t)selected<scene.size()){auto&o=scene[selected];SetWindowTextA(nameEdit,o.name.c_str());setFloat(xEdit,o.x);setFloat(yEdit,o.y);setFloat(zEdit,o.z);setFloat(scaleEdit,o.scale);}InvalidateRect(viewport,nullptr,FALSE);}
static void saveScene(){if(projectFile.empty()){status("Create or open a project first");return;}std::ofstream f(projectFile);if(!f){status("Could not save project");return;}f<<"TinyAI 1\n";for(auto&o:scene)f<<"object "<<o.name<<" "<<o.x<<" "<<o.y<<" "<<o.z<<" "<<o.rx<<" "<<o.ry<<" "<<o.rz<<" "<<o.scale<<"\n";status("Scene saved");}
static void loadScene(){if(projectFile.empty())return;std::ifstream f(projectFile);if(!f){status("Could not open project");return;}std::string h,t;f>>h;scene.clear();while(f>>t)if(t=="object"){Obj o;f>>o.name>>o.x>>o.y>>o.z>>o.rx>>o.ry>>o.rz>>o.scale;scene.push_back(o);}if(scene.empty())scene.push_back({"Cube",0,0,0,0,0,0,1});selected=0;refresh();status("Scene loaded");}
static void newProject(){char file[MAX_PATH]="MyGame.tinyproj";OPENFILENAMEA o{};o.lStructSize=sizeof(o);o.hwndOwner=mainWnd;o.lpstrFile=file;o.nMaxFile=MAX_PATH;o.lpstrFilter="Tiny AI Project\0*.tinyproj\0\0";o.Flags=OFN_OVERWRITEPROMPT;if(!GetSaveFileNameA(&o))return;projectFile=file;scene={{"Main Camera",0,0,6,0,0,0,1},{"Cube",0,0,0,0,0,0,1}};selected=1;saveScene();showEditor();}
static void openProject(){char file[MAX_PATH]={};OPENFILENAMEA o{};o.lStructSize=sizeof(o);o.hwndOwner=mainWnd;o.lpstrFile=file;o.nMaxFile=MAX_PATH;o.lpstrFilter="Tiny AI Project\0*.tinyproj\0All Files\0*.*\0\0";o.Flags=OFN_FILEMUSTEXIST;if(!GetOpenFileNameA(&o))return;projectFile=file;loadScene();showEditor();}
static POINT proj(float x,float y,float z,RECT&r){float d=z+8;if(d<1)d=1;return{(LONG)(r.right/2+x*190/d),(LONG)(r.bottom/2-y*190/d)};}
static void cube(HDC dc,const Obj&o,RECT&r,bool sel){float a=angle+o.ry*.0174533f,c=cosf(a),s=sinf(a);float v[8][3]={{-1,-1,-1},{1,-1,-1},{1,1,-1},{-1,1,-1},{-1,-1,1},{1,-1,1},{1,1,1},{-1,1,1}};POINT p[8];for(int i=0;i<8;i++){float x=v[i][0]*o.scale,y=v[i][1]*o.scale,z=v[i][2]*o.scale;float X=x*c-z*s,Z=x*s+z*c;p[i]=proj(X+o.x,y+o.y,Z+o.z,r);}int e[][2]={{0,1},{1,2},{2,3},{3,0},{4,5},{5,6},{6,7},{7,4},{0,4},{1,5},{2,6},{3,7}};HPEN pen=CreatePen(PS_SOLID,sel?3:2,sel?RGB(255,190,70):RGB(90,180,240));HGDIOBJ old=SelectObject(dc,pen);for(auto&a:e){MoveToEx(dc,p[a[0]].x,p[a[0]].y,nullptr);LineTo(dc,p[a[1]].x,p[a[1]].y);}SelectObject(dc,old);DeleteObject(pen);}
static LRESULT CALLBACK viewportProc(HWND h,UINT m,WPARAM w,LPARAM l){if(m==WM_LBUTTONDOWN){RECT r;GetClientRect(h,&r);int mx=GET_X_LPARAM(l),my=GET_Y_LPARAM(l),best=-1;float bd=45;for(int i=0;i<(int)scene.size();i++){POINT p=proj(scene[i].x,scene[i].y,scene[i].z,r);float d=hypotf(float(p.x-mx),float(p.y-my));if(d<bd){bd=d;best=i;}}if(best>=0){selected=best;refresh();}return 0;}if(m==WM_PAINT){PAINTSTRUCT ps;HDC dc=BeginPaint(h,&ps);RECT r;GetClientRect(h,&r);HBRUSH b=CreateSolidBrush(RGB(28,31,39));FillRect(dc,&r,b);DeleteObject(b);HPEN g=CreatePen(PS_SOLID,1,RGB(50,54,64));HGDIOBJ old=SelectObject(dc,g);for(int i=-10;i<=10;i++){MoveToEx(dc,r.right/2+i*35,r.bottom/2-180,nullptr);LineTo(dc,r.right/2+i*35,r.bottom/2+180);MoveToEx(dc,r.right/2-350,r.bottom/2+i*35,nullptr);LineTo(dc,r.right/2+350,r.bottom/2+i*35);}SelectObject(dc,old);DeleteObject(g);SetBkMode(dc,TRANSPARENT);SetTextColor(dc,RGB(180,185,195));TextOutA(dc,14,12,"SCENE VIEW",10);for(int i=0;i<(int)scene.size();i++)cube(dc,scene[i],r,i==selected);EndPaint(h,&ps);return 0;}return DefWindowProcA(h,m,w,l);}
static void addCube(){scene.push_back({"Cube"+std::to_string(scene.size()),0,0,0,0,0,0,1});selected=(int)scene.size()-1;refresh();status("Cube added");}
static void deleteObj(){if(selected<0||selected>=(int)scene.size())return;scene.erase(scene.begin()+selected);selected=scene.empty()?-1:std::min(selected,(int)scene.size()-1);refresh();status("Object deleted");}
static void apply(){if(selected<0)return;auto&o=scene[selected];char n[128];GetWindowTextA(nameEdit,n,128);if(n[0])o.name=n;o.x=getFloat(xEdit,o.x);o.y=getFloat(yEdit,o.y);o.z=getFloat(zEdit,o.z);o.scale=getFloat(scaleEdit,o.scale);refresh();status("Inspector applied");}
static void modeButton(int id,bool visible){ShowWindow(GetDlgItem(mainWnd,id),visible?SW_SHOW:SW_HIDE);}
static void showHub(){hub=true;for(int id:{ID_NEW,ID_OPEN,ID_RECENT,ID_SETTINGS})modeButton(id,true);for(int id:{ID_ADD,ID_DELETE,ID_SAVE,ID_LOAD,ID_BUILD,ID_PLAY,ID_HUB,ID_APPLY})modeButton(id,false);ShowWindow(viewport,SW_HIDE);ShowWindow(hierarchy,SW_HIDE);ShowWindow(nameEdit,SW_HIDE);ShowWindow(xEdit,SW_HIDE);ShowWindow(yEdit,SW_HIDE);ShowWindow(zEdit,SW_HIDE);ShowWindow(scaleEdit,SW_HIDE);InvalidateRect(mainWnd,nullptr,TRUE);status("Welcome to Tiny AI Game Engine");}
static void showEditor(){hub=false;for(int id:{ID_NEW,ID_OPEN,ID_RECENT,ID_SETTINGS})modeButton(id,false);for(int id:{ID_ADD,ID_DELETE,ID_SAVE,ID_LOAD,ID_BUILD,ID_PLAY,ID_HUB,ID_APPLY})modeButton(id,true);ShowWindow(viewport,SW_SHOW);ShowWindow(hierarchy,SW_SHOW);ShowWindow(nameEdit,SW_SHOW);ShowWindow(xEdit,SW_SHOW);ShowWindow(yEdit,SW_SHOW);ShowWindow(zEdit,SW_SHOW);ShowWindow(scaleEdit,SW_SHOW);refresh();}
static void button(const char*t,int id,int x,int y,int w,int h){CreateWindowA("BUTTON",t,WS_CHILD|WS_VISIBLE,x,y,w,h,mainWnd,(HMENU)id,GetModuleHandleA(nullptr),nullptr);}
static LRESULT CALLBACK wndProc(HWND h,UINT m,WPARAM w,LPARAM l){if(m==WM_COMMAND){int id=LOWORD(w);if(id==ID_HIER&&HIWORD(w)==LBN_SELCHANGE){selected=(int)SendMessageA(hierarchy,LB_GETCURSEL,0,0);refresh();}switch(id){case ID_NEW:newProject();break;case ID_OPEN:openProject();break;case ID_ADD:addCube();break;case ID_DELETE:deleteObj();break;case ID_SAVE:saveScene();break;case ID_LOAD:loadScene();break;case ID_APPLY:apply();break;case ID_HUB:showHub();break;case ID_PLAY:status("Play mode is not yet connected to scene execution");break;case ID_BUILD:saveScene();status("Build pipeline is not yet connected to project export");break;case ID_RECENT:status("Recent projects are not yet persisted");break;case ID_SETTINGS:status("Settings are not yet implemented");break;}}if(m==WM_TIMER){angle+=.012f;if(viewport)InvalidateRect(viewport,nullptr,FALSE);}if(m==WM_PAINT&&hub){PAINTSTRUCT ps;HDC dc=BeginPaint(h,&ps);RECT r;GetClientRect(h,&r);HBRUSH b=CreateSolidBrush(RGB(20,23,30));FillRect(dc,&r,b);DeleteObject(b);SetBkMode(dc,TRANSPARENT);SetTextColor(dc,RGB(235,238,245));HFONT f=CreateFontA(40,0,0,0,FW_BOLD,0,0,0,DEFAULT_CHARSET,0,0,0,0,"Segoe UI");HGDIOBJ old=SelectObject(dc,f);RECT t=r;t.top=45;DrawTextA(dc,"TINY AI GAME ENGINE",-1,&t,DT_CENTER|DT_TOP);SelectObject(dc,old);DeleteObject(f);SetTextColor(dc,RGB(150,160,175));t.top=105;DrawTextA(dc,"Create. Build. Play.",-1,&t,DT_CENTER|DT_TOP);EndPaint(h,&ps);return 0;}if(m==WM_DESTROY){PostQuitMessage(0);return 0;}return DefWindowProcA(h,m,w,l);}
int WINAPI WinMain(HINSTANCE hi,HINSTANCE,LPSTR,int){WNDCLASSA wc{};wc.hInstance=hi;wc.lpfnWndProc=wndProc;wc.lpszClassName="TinyAIEditor";wc.hCursor=LoadCursor(nullptr,IDC_ARROW);wc.hbrBackground=(HBRUSH)(COLOR_WINDOW+1);RegisterClassA(&wc);WNDCLASSA vc{};vc.hInstance=hi;vc.lpfnWndProc=viewportProc;vc.lpszClassName="TinyAIViewport";vc.hCursor=LoadCursor(nullptr,IDC_CROSS);RegisterClassA(&vc);mainWnd=CreateWindowA(wc.lpszClassName,"Tiny AI Game Engine",WS_OVERLAPPEDWINDOW|WS_VISIBLE,80,50,1200,760,nullptr,nullptr,hi,nullptr);
button("New Project",ID_NEW,20,150,180,42);button("Open Project",ID_OPEN,20,202,180,42);button("Recent Projects",ID_RECENT,20,254,180,42);button("Settings",ID_SETTINGS,20,306,180,42);
button("Add Cube",ID_ADD,220,32,90,30);button("Delete",ID_DELETE,315,32,75,30);button("Save",ID_SAVE,395,32,70,30);button("Load",ID_LOAD,470,32,70,30);button("Build",ID_BUILD,545,32,70,30);button("Play",ID_PLAY,620,32,70,30);button("Hub",ID_HUB,695,32,70,30);button("Apply",ID_APPLY,940,505,90,30);
viewport=CreateWindowA(vc.lpszClassName,"",WS_CHILD|WS_BORDER,220,70,700,600,mainWnd,nullptr,hi,nullptr);hierarchy=CreateWindowA("LISTBOX","",WS_CHILD|WS_BORDER|LBS_NOTIFY,940,70,230,310,mainWnd,(HMENU)ID_HIER,hi,nullptr);nameEdit=CreateWindowA("EDIT","",WS_CHILD|WS_BORDER,940,405,230,28,mainWnd,nullptr,hi,nullptr);xEdit=CreateWindowA("EDIT","0",WS_CHILD|WS_BORDER,940,440,70,28,mainWnd,nullptr,hi,nullptr);yEdit=CreateWindowA("EDIT","0",WS_CHILD|WS_BORDER,1018,440,70,28,mainWnd,nullptr,hi,nullptr);zEdit=CreateWindowA("EDIT","0",WS_CHILD|WS_BORDER,1096,440,70,28,mainWnd,nullptr,hi,nullptr);scaleEdit=CreateWindowA("EDIT","1",WS_CHILD|WS_BORDER,940,475,70,28,mainWnd,nullptr,hi,nullptr);statusWnd=CreateWindowA("STATIC","",WS_CHILD|WS_VISIBLE,20,690,1150,24,mainWnd,nullptr,hi,nullptr);scene={{"Main Camera",0,0,6,0,0,0,1},{"Cube",0,0,0,0,0,0,1}};selected=1;SetTimer(mainWnd,1,16,nullptr);showHub();MSG msg;while(GetMessageA(&msg,nullptr,0,0)){TranslateMessage(&msg);DispatchMessageA(&msg);}return 0;}
