#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <commdlg.h>
#include <fstream>
#include <string>
#include <vector>
#include <cmath>
#include <algorithm>

struct Obj { std::string name; float x=0,y=0,z=0,rx=0,ry=0,rz=0,scale=1; };
static std::vector<Obj> scene;
static int selected=-1;
static HWND mainWnd, viewport, hierarchy, statusWnd, nameEdit, xEdit, yEdit, zEdit, sxEdit, syEdit, szEdit;
static std::string projectDir, projectFile;
static bool hub=true;
static float angle=0;

enum { ID_NEW=101,ID_OPEN,ID_RECENT,ID_SETTINGS,ID_ADD,ID_DELETE,ID_SAVE,ID_LOAD,ID_BUILD,ID_PLAY,ID_HUB,ID_APPLY,ID_VIEW=200 };

static void setStatus(const std::string&s){if(statusWnd)SetWindowTextA(statusWnd,s.c_str());}
static void refreshHierarchy(){if(!hierarchy)return;SendMessageA(hierarchy,LB_RESETCONTENT,0,0);for(auto&o:scene)SendMessageA(hierarchy,LB_ADDSTRING,0,(LPARAM)o.name.c_str());if(selected>=0)SendMessageA(hierarchy,LB_SETCURSEL,selected,0);}
static void editSet(HWND h,float v){char b[64];sprintf_s(b,"%.3f",v);SetWindowTextA(h,b);}
static void refreshInspector(){if(selected<0||selected>=(int)scene.size()){SetWindowTextA(nameEdit,"");return;}auto&o=scene[selected];SetWindowTextA(nameEdit,o.name.c_str());editSet(xEdit,o.x);editSet(yEdit,o.y);editSet(zEdit,o.z);editSet(sxEdit,o.scale);editSet(syEdit,o.scale);editSet(szEdit,o.scale);}
static float readFloat(HWND h,float fallback){char b[64];GetWindowTextA(h,b,64);char*e=nullptr;float v=strtof(b,&e);return e&&e!=b?v:fallback;}
static void applyInspector(){if(selected<0||selected>=(int)scene.size())return;auto&o=scene[selected];char b[128];GetWindowTextA(nameEdit,b,128);if(b[0])o.name=b;o.x=readFloat(xEdit,o.x);o.y=readFloat(yEdit,o.y);o.z=readFloat(zEdit,o.z);o.scale=readFloat(sxEdit,o.scale);refreshHierarchy();InvalidateRect(viewport,nullptr,FALSE);setStatus("Inspector changes applied");}
static void saveScene(){if(projectFile.empty()){setStatus("Create or open a project first");return;}std::ofstream f(projectFile);f<<"TinyAI 1\n";for(auto&o:scene)f<<"object "<<o.name<<" "<<o.x<<" "<<o.y<<" "<<o.z<<" "<<o.rx<<" "<<o.ry<<" "<<o.rz<<" "<<o.scale<<"\n";setStatus("Scene saved");}
static void loadScene(){if(projectFile.empty())return;std::ifstream f(projectFile);if(!f){setStatus("No scene file found");return;}std::string h,t;f>>h;scene.clear();while(f>>t)if(t=="object"){Obj o;f>>o.name>>o.x>>o.y>>o.z>>o.rx>>o.ry>>o.rz>>o.scale;scene.push_back(o);}if(scene.empty())scene.push_back({"Cube",0,0,0,0,0,0,1});selected=0;refreshHierarchy();refreshInspector();InvalidateRect(viewport,nullptr,FALSE);setStatus("Scene loaded");}
static void createProject(){char path[MAX_PATH]={};OPENFILENAMEA ofn{};ofn.lStructSize=sizeof(ofn);ofn.hwndOwner=mainWnd;ofn.lpstrFile=path;ofn.nMaxFile=MAX_PATH;ofn.lpstrTitle="Choose project folder";ofn.Flags=OFN_EXPLORER|OFN_PATHMUSTEXIST;/* Folder picker is intentionally replaced by a save-file flow for broad Win32 compatibility. */
char file[MAX_PATH]="MyGame.tinyproj";ofn.lpstrFile=file;ofn.nMaxFile=MAX_PATH;ofn.lpstrFilter="Tiny AI Project\0*.tinyproj\0\0";ofn.Flags=OFN_OVERWRITEPROMPT|OFN_PATHMUSTEXIST;if(!GetSaveFileNameA(&ofn))return;projectDir=file;auto p=projectDir.find_last_of("\\/");if(p!=std::string::npos)projectDir.resize(p);projectFile=file;scene={{"Main Camera",0,0,6,0,0,0,1},{"Cube",0,0,0,0,0,0,1}};selected=1;saveScene();hub=false;showEditor();}
static void openProject(){char file[MAX_PATH]={};OPENFILENAMEA ofn{};ofn.lStructSize=sizeof(ofn);ofn.hwndOwner=mainWnd;ofn.lpstrFile=file;ofn.nMaxFile=MAX_PATH;ofn.lpstrFilter="Tiny AI Project\0*.tinyproj\0All Files\0*.*\0\0";ofn.Flags=OFN_FILEMUSTEXIST;if(!GetOpenFileNameA(&ofn))return;projectFile=file;hub=false;loadScene();showEditor();}
static POINT project(float x,float y,float z,RECT&r){float d=z+7;if(d<1)d=1;return {(LONG)((r.right-r.left)/2+x*180/d),(LONG)((r.bottom-r.top)/2-y*180/d)};}
static void drawGrid(HDC dc,RECT&r){HPEN p=CreatePen(PS_SOLID,1,RGB(45,50,60));auto old=SelectObject(dc,p);for(int i=-10;i<=10;i++){int a=(r.right+r.left)/2+i*35;MoveToEx(dc,a,(r.bottom+r.top)/2-175,nullptr);LineTo(dc,a,(r.bottom+r.top)/2+175);int b=(r.bottom+r.top)/2+i*35;MoveToEx(dc,(r.right+r.left)/2-350,b,nullptr);LineTo(dc,(r.right+r.left)/2+350,b);}SelectObject(dc,old);DeleteObject(p);}
static void drawCube(HDC dc,const Obj&o,RECT&r,bool sel){float a=angle+o.ry*.01745f,c=cosf(a),s=sinf(a);float v[8][3]={{-1,-1,-1},{1,-1,-1},{1,1,-1},{-1,1,-1},{-1,-1,1},{1,-1,1},{1,1,1},{-1,1,1}};POINT q[8];for(int i=0;i<8;i++){float x=v[i][0]*o.scale,y=v[i][1]*o.scale,z=v[i][2]*o.scale;float X=x*c-z*s,Z=x*s+z*c;q[i]=project(X+o.x,y+o.y,Z+o.z,r);}int e[][2]={{0,1},{1,2},{2,3},{3,0},{4,5},{5,6},{6,7},{7,4},{0,4},{1,5},{2,6},{3,7}};HPEN pen=CreatePen(PS_SOLID,sel?3:2,sel?RGB(255,190,70):RGB(90,180,240));auto old=SelectObject(dc,pen);for(auto&v:e){MoveToEx(dc,q[v[0]].x,q[v[0]].y,nullptr);LineTo(dc,q[v[1]].x,q[v[1]].y);}SelectObject(dc,old);DeleteObject(pen);}
static LRESULT CALLBACK viewProc(HWND h,UINT m,WPARAM w,LPARAM l){if(m==WM_LBUTTONDOWN){int mx=GET_X_LPARAM(l),my=GET_Y_LPARAM(l);RECT r;GetClientRect(h,&r);int best=-1;float bd=35;for(int i=0;i<(int)scene.size();i++){POINT p=project(scene[i].x,scene[i].y,scene[i].z,r);float d=sqrtf(float((p.x-mx)*(p.x-mx)+(p.y-my)*(p.y-my)));if(d<bd){bd=d;best=i;}}if(best>=0){selected=best;refreshHierarchy();refreshInspector();InvalidateRect(h,nullptr,FALSE);}return 0;}if(m==WM_PAINT){PAINTSTRUCT ps;HDC dc=BeginPaint(h,&ps);RECT r;GetClientRect(h,&r);HBRUSH b=CreateSolidBrush(RGB(27,30,38));FillRect(dc,&r,b);DeleteObject(b);SetBkMode(dc,TRANSPARENT);SetTextColor(dc,RGB(160,170,185));TextOutA(dc,15,12,"SCENE VIEW",10);drawGrid(dc,r);for(int i=0;i<(int)scene.size();i++)drawCube(dc,scene[i],r,i==selected);EndPaint(h,&ps);return 0;}return DefWindowProcA(h,m,w,l);}
static void addCube(){scene.push_back({"Cube"+std::to_string(scene.size()),0,0,0,0,0,0,1});selected=(int)scene.size()-1;refreshHierarchy();refreshInspector();InvalidateRect(viewport,nullptr,FALSE);setStatus("Cube added");}
static void deleteSelected(){if(selected<0||selected>=(int)scene.size())return;scene.erase(scene.begin()+selected);selected=scene.empty()?-1:std::min(selected,(int)scene.size()-1);refreshHierarchy();refreshInspector();InvalidateRect(viewport,nullptr,FALSE);setStatus("Object deleted");}
static void buildGame(){saveScene();if(projectDir.empty()){setStatus("Save the project before building");return;}CreateDirectoryA((projectDir+"\\Build").c_str(),nullptr);setStatus("Build prepared in project Build folder");}
static void showHub();
static void showEditor(){hub=false;ShowWindow(viewport,SW_SHOW);ShowWindow(hierarchy,SW_SHOW);ShowWindow(nameEdit,SW_SHOW);ShowWindow(xEdit,SW_SHOW);ShowWindow(yEdit,SW_SHOW);ShowWindow(zEdit,SW_SHOW);ShowWindow(sxEdit,SW_SHOW);ShowWindow(syEdit,SW_SHOW);ShowWindow(szEdit,SW_SHOW);InvalidateRect(mainWnd,nullptr,TRUE);}
static void showHub(){hub=true;ShowWindow(viewport,SW_HIDE);ShowWindow(hierarchy,SW_HIDE);ShowWindow(nameEdit,SW_HIDE);ShowWindow(xEdit,SW_HIDE);ShowWindow(yEdit,SW_HIDE);ShowWindow(zEdit,SW_HIDE);ShowWindow(sxEdit,SW_HIDE);ShowWindow(syEdit,SW_HIDE);ShowWindow(szEdit,SW_HIDE);InvalidateRect(mainWnd,nullptr,TRUE);}
static void addButton(HWND p,const char*t,int id,int x,int y,int w,int h){CreateWindowA("BUTTON",t,WS_CHILD|WS_VISIBLE|BS_PUSHBUTTON,x,y,w,h,p,(HMENU)id,GetModuleHandleA(nullptr),nullptr);}
static LRESULT CALLBACK wndProc(HWND h,UINT m,WPARAM w,LPARAM l){if(m==WM_COMMAND){switch(LOWORD(w)){case ID_NEW:createProject();break;case ID_OPEN:openProject();break;case ID_ADD:addCube();break;case ID_DELETE:deleteSelected();break;case ID_SAVE:saveScene();break;case ID_LOAD:loadScene();break;case ID_BUILD:buildGame();break;case ID_PLAY:if(projectFile.empty())setStatus("Save a project first");else{saveScene();ShellExecuteA(h,"open","TinyAIRuntime.exe",nullptr,projectDir.empty()?nullptr:projectDir.c_str(),SW_SHOWNORMAL);}break;case ID_HUB:showHub();break;case ID_APPLY:applyInspector();break;case ID_RECENT:setStatus("Recent projects will appear here as projects are opened");break;case ID_SETTINGS:setStatus("Settings are planned for a later editor version");break;}}if(m==WM_TIMER){angle+=.012f;if(viewport)InvalidateRect(viewport,nullptr,FALSE);}if(m==WM_DESTROY){PostQuitMessage(0);return 0;}if(m==WM_PAINT&&hub){PAINTSTRUCT ps;HDC dc=BeginPaint(h,&ps);RECT r;GetClientRect(h,&r);HBRUSH b=CreateSolidBrush(RGB(20,23,30));FillRect(dc,&r,b);DeleteObject(b);SetBkMode(dc,TRANSPARENT);SetTextColor(dc,RGB(235,238,245));HFONT big=CreateFontA(42,0,0,0,FW_BOLD,FALSE,FALSE,FALSE,DEFAULT_CHARSET,OUT_DEFAULT_PRECIS,CLIP_DEFAULT_PRECIS,DEFAULT_QUALITY,DEFAULT_PITCH,"Segoe UI");auto old=SelectObject(dc,big);DrawTextA(dc,"TINY AI GAME ENGINE",-1,&r,DT_CENTER|DT_TOP);SelectObject(dc,old);DeleteObject(big);SetTextColor(dc,RGB(150,160,175));RECT sub=r;sub.top=70;DrawTextA(dc,"Create. Build. Play.",-1,&sub,DT_CENTER|DT_TOP);EndPaint(h,&ps);return 0;}return DefWindowProcA(h,m,w,l);}
int WINAPI WinMain(HINSTANCE hi,HINSTANCE,LPSTR,int){WNDCLASSA wc{};wc.hInstance=hi;wc.lpfnWndProc=wndProc;wc.lpszClassName="TinyAIEditor";wc.hCursor=LoadCursor(nullptr,IDC_ARROW);wc.hbrBackground=(HBRUSH)(COLOR_WINDOW+1);RegisterClassA(&wc);WNDCLASSA vc{};vc.hInstance=hi;vc.lpfnWndProc=viewProc;vc.lpszClassName="TinyAIViewport";vc.hCursor=LoadCursor(nullptr,IDC_CROSS);RegisterClassA(&vc);mainWnd=CreateWindowA(wc.lpszClassName,"Tiny AI Game Engine",WS_OVERLAPPEDWINDOW|WS_VISIBLE,100,70,1200,760,nullptr,nullptr,hi,nullptr);
addButton(mainWnd,"New Project",ID_NEW,20,105,180,42);addButton(mainWnd,"Open Project",ID_OPEN,20,157,180,42);addButton(mainWnd,"Recent Projects",ID_RECENT,20,209,180,42);addButton(mainWnd,"Settings",ID_SETTINGS,20,261,180,42);
viewport=CreateWindowA(vc.lpszClassName,"",WS_CHILD|WS_VISIBLE|WS_BORDER,220,70,700,610,mainWnd,nullptr,hi,nullptr);hierarchy=CreateWindowA("LISTBOX","",WS_CHILD|WS_VISIBLE|WS_BORDER|LBS_NOTIFY,930,70,240,300,mainWnd,nullptr,hi,nullptr);nameEdit=CreateWindowA("EDIT","",WS_CHILD|WS_BORDER,930,395,240,28,mainWnd,nullptr,hi,nullptr);xEdit=CreateWindowA("EDIT","0",WS_CHILD|WS_BORDER,930,430,75,28,mainWnd,nullptr,hi,nullptr);yEdit=CreateWindowA("EDIT","0",WS_CHILD|WS_BORDER,1012,430,75,28,mainWnd,nullptr,hi,nullptr);zEdit=CreateWindowA("EDIT","0",WS_CHILD|WS_BORDER,1094,430,75,28,mainWnd,nullptr,hi,nullptr);sxEdit=CreateWindowA("EDIT","1",WS_CHILD|WS_BORDER,930,465,75,28,mainWnd,nullptr,hi,nullptr);syEdit=CreateWindowA("EDIT","1",WS_CHILD|WS_BORDER,1012,465,75,28,mainWnd,nullptr,hi,nullptr);szEdit=CreateWindowA("EDIT","1",WS_CHILD|WS_BORDER,1094,465,75,28,mainWnd,nullptr,hi,nullptr);addButton(mainWnd,"Apply",ID_APPLY,930,500,110,30);addButton(mainWnd,"Add Cube",ID_ADD,220,30,100,30);addButton(mainWnd,"Delete",ID_DELETE,325,30,80,30);addButton(mainWnd,"Save",ID_SAVE,410,30,70,30);addButton(mainWnd,"Load",ID_LOAD,485,30,70,30);addButton(mainWnd,"Build",ID_BUILD,560,30,80,30);addButton(mainWnd,"Play",ID_PLAY,645,30,80,30);addButton(mainWnd,"Hub",ID_HUB,730,30,70,30);statusWnd=CreateWindowA("STATIC","Welcome",WS_CHILD|WS_VISIBLE,20,695,1150,24,mainWnd,nullptr,hi,nullptr);SetTimer(mainWnd,1,16,nullptr);scene={{"Main Camera",0,0,6,0,0,0,1},{"Cube",0,0,0,0,0,0,1}};selected=1;refreshHierarchy();refreshInspector();showHub();MSG msg;while(GetMessageA(&msg,nullptr,0,0)){TranslateMessage(&msg);DispatchMessageA(&msg);}return 0;}
