#include "engine.hpp"
#include <d3dcompiler.h>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <algorithm>
#include <cmath>
#include <cstring>
namespace tiny {
std::wstring widen(const std::string&s){if(s.empty())return{};int n=MultiByteToWideChar(CP_UTF8,0,s.data(),(int)s.size(),nullptr,0);std::wstring r(n,L' ');MultiByteToWideChar(CP_UTF8,0,s.data(),(int)s.size(),r.data(),n);return r;}
std::string narrow(const std::wstring&s){if(s.empty())return{};int n=WideCharToMultiByte(CP_UTF8,0,s.data(),(int)s.size(),nullptr,0,nullptr,nullptr);std::string r(n,' ');WideCharToMultiByte(CP_UTF8,0,s.data(),(int)s.size(),r.data(),n,nullptr,nullptr);return r;}
bool writeUtf8File(const std::wstring&p,const std::string&d){std::ofstream f(std::filesystem::path(p),std::ios::binary);if(!f)return false;f.write(d.data(),(std::streamsize)d.size());return f.good();}
bool readUtf8File(const std::wstring&p,std::string&d){std::ifstream f(std::filesystem::path(p),std::ios::binary);if(!f)return false;std::ostringstream o;o<<f.rdbuf();d=o.str();return true;}
std::string kindName(EntityKind k){switch(k){case EntityKind::Cube:return"Cube";case EntityKind::Sphere:return"Sphere";case EntityKind::Plane:return"Plane";case EntityKind::Camera:return"Camera";case EntityKind::DirectionalLight:return"Directional Light";case EntityKind::PointLight:return"Point Light";case EntityKind::SpotLight:return"Spot Light";}return"Unknown";}
std::string serialize(const Scene&sc){std::ostringstream o;o<<"TINYSCENE 2\n"<<sc.name<<' '<<sc.cameraId<<'\n';for(const auto&e:sc.entities){auto&p=e.transform.position;auto&r=e.transform.rotation;auto&z=e.transform.scale;auto&c=e.material.color;auto&l=e.light.color;o<<e.id<<' '<<int(e.kind)<<' '<<e.name<<' '<<p.x<<' '<<p.y<<' '<<p.z<<' '<<r.x<<' '<<r.y<<' '<<r.z<<' '<<z.x<<' '<<z.y<<' '<<z.z<<' '<<c.x<<' '<<c.y<<' '<<c.z<<' '<<e.material.roughness<<' '<<e.material.metallic<<' '<<l.x<<' '<<l.y<<' '<<l.z<<' '<<e.light.intensity<<' '<<e.light.range<<' '<<e.light.inner<<' '<<e.light.outer<<' '<<e.light.shadows<<' '<<e.dynamic<<' '<<e.visible<<' '<<e.script<<'\n';}return o.str();}
bool deserialize(const std::string&t,Scene&sc,std::string&err){std::istringstream in(t);std::string magic;if(!(in>>magic)||magic!="TINYSCENE"){err="Not a Tiny scene.";return false;}int ver;if(!(in>>ver)||ver!=2){err="Unsupported scene version.";return false;}if(!(in>>sc.name>>sc.cameraId)){err="Invalid scene header.";return false;}sc.entities.clear();sc.nextId=1;while(true){Entity e;int k;if(!(in>>e.id)){if(in.eof())break;err="Invalid entity id.";return false;}if(!(in>>k>>e.name>>e.transform.position.x>>e.transform.position.y>>e.transform.position.z>>e.transform.rotation.x>>e.transform.rotation.y>>e.transform.rotation.z>>e.transform.scale.x>>e.transform.scale.y>>e.transform.scale.z>>e.material.color.x>>e.material.color.y>>e.material.color.z>>e.material.roughness>>e.material.metallic>>e.light.color.x>>e.light.color.y>>e.light.color.z>>e.light.intensity>>e.light.range>>e.light.inner>>e.light.outer>>e.light.shadows>>e.dynamic>>e.visible>>e.script){err="Invalid entity data.";return false;}if(k<0||k>6){err="Invalid entity type.";return false;}e.kind=(EntityKind)k;sc.entities.push_back(e);sc.nextId=(std::max)(sc.nextId,e.id+1);}return true;}
static const char* shader=R"HLSL(cbuffer C:register(b0){float4x4 mvp;float4x4 model;float4 base;float4 light;float4 cam;};struct I{float3 p:POSITION;float3 n:NORMAL;};struct O{float4 p:SV_POSITION;float3 n:NORMAL;float3 wp:TEXCOORD0;};O VS(I i){O o;float4 wp=mul(float4(i.p,1),model);o.p=mul(wp,mvp);o.wp=wp.xyz;o.n=normalize(mul(float4(i.n,0),model).xyz);return o;}float4 PS(O i):SV_TARGET{float3 n=normalize(i.n);float3 l=normalize(-light.xyz);float3 v=normalize(cam.xyz-i.wp);float3 h=normalize(l+v);float d=max(0,dot(n,l));float s=pow(max(0,dot(n,h)),32)*.2;return float4(saturate(base.rgb*(.12+d*light.w)+s),base.a);})HLSL";
struct Vertex{XMFLOAT3 p,n;};struct Constant{XMFLOAT4X4 mvp,model;XMFLOAT4 base,light,cam;};
static std::vector<Vertex> cube(){const XMFLOAT3 p[]={{-1,-1,-1},{-1,1,-1},{1,1,-1},{1,-1,-1},{-1,-1,1},{1,-1,1},{1,1,1},{-1,1,1}};const int f[]={0,1,2,0,2,3,4,5,6,4,6,7,0,4,7,0,7,1,3,2,6,3,6,5,1,7,6,1,6,2,0,3,5,0,5,4};std::vector<Vertex>v;v.reserve(36);for(int i:f){XMFLOAT3 n=XMVectorGetX(XMVector3Normalize(XMVector3Cross(XMLoadFloat3(&p[(i/3)*3]),XMLoadFloat3(&p[(i/3)*3+1]))))>0?XMFLOAT3{0,1,0}:XMFLOAT3{0,1,0};(void)n;v.push_back({p[i],XMFLOAT3{0,0,1}});}return v;}
bool Graphics::initialize(HWND h,int w,int ht,bool vs){hwnd_=h;width_=(std::max)(1,w);height_=(std::max)(1,ht);vsync_=vs;DXGI_SWAP_CHAIN_DESC d{};d.BufferCount=2;d.BufferDesc.Width=width_;d.BufferDesc.Height=height_;d.BufferDesc.Format=DXGI_FORMAT_R8G8B8A8_UNORM;d.BufferUsage=DXGI_USAGE_RENDER_TARGET_OUTPUT;d.OutputWindow=h;d.SampleDesc.Count=1;d.Windowed=TRUE;d.SwapEffect=DXGI_SWAP_EFFECT_FLIP_DISCARD;D3D_FEATURE_LEVEL fl{};if(FAILED(D3D11CreateDeviceAndSwapChain(nullptr,D3D_DRIVER_TYPE_HARDWARE,nullptr,0,nullptr,0,D3D11_SDK_VERSION,&d,&swap_,&device_,&fl,&context_)))return false;return makeShaders()&&makeBuffers()&&makeTargets();}
bool Graphics::makeShaders(){ComPtr<ID3DBlob>a,b,e;if(FAILED(D3DCompile(shader,strlen(shader),"tiny",nullptr,nullptr,"VS","vs_5_0",0,0,&a,&e)))return false;if(FAILED(D3DCompile(shader,strlen(shader),"tiny",nullptr,nullptr,"PS","ps_5_0",0,0,&b,&e)))return false;if(FAILED(device_->CreateVertexShader(a->GetBufferPointer(),a->GetBufferSize(),nullptr,&vs_)))return false;if(FAILED(device_->CreatePixelShader(b->GetBufferPointer(),b->GetBufferSize(),nullptr,&ps_)))return false;D3D11_INPUT_ELEMENT_DESC d[]={{"POSITION",0,DXGI_FORMAT_R32G32B32_FLOAT,0,0,D3D11_INPUT_PER_VERTEX_DATA,0},{"NORMAL",0,DXGI_FORMAT_R32G32B32_FLOAT,0,12,D3D11_INPUT_PER_VERTEX_DATA,0}};return SUCCEEDED(device_->CreateInputLayout(d,2,a->GetBufferPointer(),a->GetBufferSize(),&layout_));}
bool Graphics::makeBuffers(){auto v=cube();D3D11_BUFFER_DESC d{};d.Usage=D3D11_USAGE_DEFAULT;d.ByteWidth=(UINT)(v.size()*sizeof(Vertex));d.BindFlags=D3D11_BIND_VERTEX_BUFFER;D3D11_SUBRESOURCE_DATA init{v.data(),0,0};if(FAILED(device_->CreateBuffer(&d,&init,&vb_)))return false;d.ByteWidth=sizeof(Constant);d.BindFlags=D3D11_BIND_CONSTANT_BUFFER;d.CPUAccessFlags=0;return SUCCEEDED(device_->CreateBuffer(&d,nullptr,&cb_));}
bool Graphics::makeTargets(){ComPtr<ID3D11Texture2D>b;if(FAILED(swap_->GetBuffer(0,IID_PPV_ARGS(&b))))return false;if(FAILED(device_->CreateRenderTargetView(b.Get(),nullptr,&rtv_)))return false;D3D11_TEXTURE2D_DESC d{};d.Width=width_;d.Height=height_;d.MipLevels=1;d.ArraySize=1;d.Format=DXGI_FORMAT_D24_UNORM_S8_UINT;d.SampleDesc.Count=1;d.BindFlags=D3D11_BIND_DEPTH_STENCIL;if(FAILED(device_->CreateTexture2D(&d,nullptr,&depth_)))return false;return SUCCEEDED(device_->CreateDepthStencilView(depth_.Get(),nullptr,&dsv_));}
void Graphics::resize(int w,int h){if(!swap_||w<1||h<1)return;context_->OMSetRenderTargets(0,nullptr,nullptr);rtv_.Reset();dsv_.Reset();depth_.Reset();width_=w;height_=h;if(FAILED(swap_->ResizeBuffers(0,w,h,DXGI_FORMAT_UNKNOWN,0)))return;makeTargets();}
void Graphics::beginFrame(const float c[4]){if(!ready()&&swap_)makeTargets();context_->OMSetRenderTargets(1,rtv_.GetAddressOf(),dsv_.Get());context_->ClearRenderTargetView(rtv_.Get(),c);context_->ClearDepthStencilView(dsv_.Get(),D3D11_CLEAR_DEPTH|D3D11_CLEAR_STENCIL,1,0);D3D11_VIEWPORT v{0,0,(float)width_,(float)height_,0,1};context_->RSSetViewports(1,&v);if(!raster_){D3D11_RASTERIZER_DESC r{};r.FillMode=D3D11_FILL_SOLID;r.CullMode=D3D11_CULL_BACK;r.FrontCounterClockwise=FALSE;device_->CreateRasterizerState(&r,&raster_);}context_->RSSetState(raster_.Get());}
void Graphics::drawEntity(const Entity&e,const XMMATRIX&view,const XMMATRIX&proj){if(e.kind==EntityKind::Camera||e.kind==EntityKind::DirectionalLight||e.kind==EntityKind::PointLight||e.kind==EntityKind::SpotLight)return;XMMATRIX m=XMMatrixScaling(e.transform.scale.x,e.transform.scale.y,e.transform.scale.z)*XMMatrixRotationRollPitchYaw(XMConvertToRadians(e.transform.rotation.x),XMConvertToRadians(e.transform.rotation.y),XMConvertToRadians(e.transform.rotation.z))*XMMatrixTranslation(e.transform.position.x,e.transform.position.y,e.transform.position.z);Constant c{};XMStoreFloat4x4(&c.model,XMMatrixTranspose(m));XMStoreFloat4x4(&c.mvp,XMMatrixTranspose(m*view*proj));c.base=e.material.color;c.light=XMFLOAT4(-.45f,-.9f,-.3f,1.2f);c.cam=XMFLOAT4(0,2,-8,1);context_->UpdateSubresource(cb_.Get(),0,nullptr,&c,0,0);UINT stride=sizeof(Vertex),off=0;context_->IASetVertexBuffers(0,1,vb_.GetAddressOf(),&stride,&off);context_->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST);context_->IASetInputLayout(layout_.Get());context_->VSSetShader(vs_.Get(),nullptr,0);context_->PSSetShader(ps_.Get(),nullptr,0);context_->VSSetConstantBuffers(0,1,cb_.GetAddressOf());context_->PSSetConstantBuffers(0,1,cb_.GetAddressOf());context_->Draw(36,0);}
void Graphics::drawScene(const Scene&s,const XMMATRIX&v,const XMMATRIX&p){for(const auto&e:s.entities)if(e.visible)drawEntity(e,v,p);}
void Graphics::endFrame(){if(swap_)swap_->Present(vsync_?1:0,0);}
bool Engine::initialize(HWND h,int w,int ht){width_=(std::max)(1,w);height_=(std::max)(1,ht);if(!gfx_.initialize(h,width_,height_,true))return false;scene_.entities.clear();scene_.nextId=1;Entity c;c.id=scene_.nextId++;c.name="MainCamera";c.kind=EntityKind::Camera;c.transform.position={0,2,-8};scene_.cameraId=c.id;scene_.entities.push_back(c);Entity l;l.id=scene_.nextId++;l.name="Sun";l.kind=EntityKind::DirectionalLight;l.transform.rotation={35,-35,0};scene_.entities.push_back(l);Entity p;p.id=scene_.nextId++;p.name="Ground";p.kind=EntityKind::Plane;p.transform.scale={6,.1f,6};p.material.color={.3f,.34f,.38f,1};scene_.entities.push_back(p);Entity q;q.id=scene_.nextId++;q.name="Player";q.kind=EntityKind::Cube;q.transform.position={0,1,0};q.dynamic=true;scene_.entities.push_back(q);return true;}
void Engine::resize(int w,int h){width_=(std::max)(1,w);height_=(std::max)(1,h);gfx_.resize(width_,height_);}
void Engine::play(bool v){playing_=v;if(!v)time_=0;}
void Engine::tick(float dt){if(playing_)simulate(dt);}
void Engine::simulate(float dt){for(auto&e:scene_.entities)if(e.dynamic){float x=0,z=0;if(keyDown('W'))z+=1;if(keyDown('S'))z-=1;if(keyDown('A'))x-=1;if(keyDown('D'))x+=1;float n=std::sqrt(x*x+z*z);if(n>0){x/=n;z/=n;e.transform.position.x+=x*5*dt;e.transform.position.z+=z*5*dt;}}}
XMMATRIX Engine::cameraView()const{auto it=std::find_if(scene_.entities.begin(),scene_.entities.end(),[&](const auto&e){return e.id==scene_.cameraId;});XMFLOAT3 p=it==scene_.entities.end()?XMFLOAT3{0,2,-8}:it->transform.position;return XMMatrixLookAtLH(XMLoadFloat3(&p),XMVectorSet(p.x,p.y,p.z+1,1),XMVectorSet(0,1,0,0));}
XMMATRIX Engine::cameraProjection()const{return XMMatrixPerspectiveFovLH(XMConvertToRadians(60.0f),float(width_)/float(height_),.1f,1000.0f);}
void Engine::render(){if(!gfx_.ready())return;float c[]={.045f,.055f,.075f,1};gfx_.beginFrame(c);gfx_.drawScene(scene_,cameraView(),cameraProjection());gfx_.endFrame();}
}
