#include "engine.hpp"
#include <d3dcompiler.h>
#include <fstream>
#include <sstream>
#include <filesystem>
#include <algorithm>
#include <cmath>
#include <cstring>
namespace tiny {
std::wstring widen(const std::string& s){if(s.empty())return{};int n=MultiByteToWideChar(CP_UTF8,0,s.data(),(int)s.size(),nullptr,0);std::wstring r(n,L' ');MultiByteToWideChar(CP_UTF8,0,s.data(),(int)s.size(),r.data(),n);return r;}
std::string narrow(const std::wstring& s){if(s.empty())return{};int n=WideCharToMultiByte(CP_UTF8,0,s.data(),(int)s.size(),nullptr,0,nullptr,nullptr);std::string r(n,' ');WideCharToMultiByte(CP_UTF8,0,s.data(),(int)s.size(),r.data(),n,nullptr,nullptr);return r;}
bool writeUtf8File(const std::wstring&p,const std::string&d){std::ofstream f(std::filesystem::path(p),std::ios::binary);if(!f)return false;f.write(d.data(),(std::streamsize)d.size());return !!f;}
bool readUtf8File(const std::wstring&p,std::string&d){std::ifstream f(std::filesystem::path(p),std::ios::binary);if(!f)return false;std::ostringstream o;o<<f.rdbuf();d=o.str();return true;}
std::string kindName(EntityKind k){switch(k){case EntityKind::Cube:return"Cube";case EntityKind::Sphere:return"Sphere";case EntityKind::Plane:return"Plane";case EntityKind::Camera:return"Camera";case EntityKind::DirectionalLight:return"Directional Light";case EntityKind::PointLight:return"Point Light";default:return"Spot Light";}}
std::string serialize(const Scene& sc){std::ostringstream o;o<<"TINYSCENE 2\nname "<<sc.name<<"\ncamera "<<sc.cameraId<<"\n";for(auto&e:sc.entities)o<<"entity "<<e.id<<' '<<int(e.kind)<<' '<<e.name.size()<<' '<<e.name<<' '<<e.transform.position.x<<' '<<e.transform.position.y<<' '<<e.transform.position.z<<' '<<e.transform.rotation.x<<' '<<e.transform.rotation.y<<' '<<e.transform.rotation.z<<' '<<e.transform.scale.x<<' '<<e.transform.scale.y<<' '<<e.transform.scale.z<<' '<<e.material.color.x<<' '<<e.material.color.y<<' '<<e.material.color.z<<' '<<e.material.roughness<<' '<<e.material.metallic<<' '<<e.light.color.x<<' '<<e.light.color.y<<' '<<e.light.color.z<<' '<<e.light.intensity<<' '<<e.light.range<<' '<<e.light.inner<<' '<<e.light.outer<<' '<<e.light.shadows<<' '<<e.dynamic<<' '<<e.visible<<' '<<e.script<<'\n';return o.str();}
bool deserialize(const std::string& text,Scene& sc,std::string&err){std::istringstream in(text);std::string magic,key;if(!(in>>magic)||magic!="TINYSCENE"){err="Not a Tiny scene file.";return false;}int ver;if(!(in>>ver)||ver!=2){err="Unsupported scene version.";return false;}if(!(in>>key>>sc.name)||key!="name"||!(in>>key>>sc.cameraId)||key!="camera"){err="Invalid scene header.";return false;}sc.entities.clear();sc.nextId=1;while(in>>key){if(key!="entity"){err="Unexpected token in scene.";return false;}Entity e;int kind;size_t len;if(!(in>>e.id>>kind>>len)){err="Invalid entity header.";return false;}in.get();std::getline(in,e.name,' ');if(e.name.size()!=len){err="Invalid entity name.";return false;}e.kind=(EntityKind)kind;if(!(in>>e.transform.position.x>>e.transform.position.y>>e.transform.position.z>>e.transform.rotation.x>>e.transform.rotation.y>>e.transform.rotation.z>>e.transform.scale.x>>e.transform.scale.y>>e.transform.scale.z>>e.material.color.x>>e.material.color.y>>e.material.color.z>>e.material.roughness>>e.material.metallic>>e.light.color.x>>e.light.color.y>>e.light.color.z>>e.light.intensity>>e.light.range>>e.light.inner>>e.light.outer>>e.light.shadows>>e.dynamic>>e.visible>>e.script){err="Invalid entity data.";return false;}sc.entities.push_back(e);sc.nextId=std::max(sc.nextId,e.id+1);}return true;}
static const char* HLSL=R"(cbuffer Frame:register(b0){float4x4 mvp;float4x4 model;float4 base;float4 lightDir;float4 lightColor;float4 camera;};struct VSIn{float3 p:POSITION;float3 n:NORMAL;};struct VSOut{float4 p:SV_POSITION;float3 n:NORMAL;float3 wp:TEXCOORD0;};VSOut VS(VSIn i){VSOut o;float4 wp=mul(float4(i.p,1),model);o.p=mul(wp,mvp);o.wp=wp.xyz;o.n=normalize(mul(float4(i.n,0),model).xyz);return o;}float4 PS(VSOut i):SV_TARGET{float3 n=normalize(i.n);float3 l=normalize(-lightDir.xyz);float nd=max(0,dot(n,l));float3 v=normalize(camera.xyz-i.wp);float3 h=normalize(l+v);float spec=pow(max(0,dot(n,h)),48)*.25;float3 c=base.rgb*(.12+nd*lightColor.w*lightColor.rgb)+spec;return float4(saturate(c),base.a);})";
struct CBuf{XMFLOAT4X4 mvp,model;XMFLOAT4 base,lightDir,lightColor,camera;};struct V{XMFLOAT3 p,n;};
static std::vector<V> cubeVerts(){const XMFLOAT3 p[8]={{-1,-1,-1},{-1,1,-1},{1,1,-1},{1,-1,-1},{-1,-1,1},{1,-1,1},{1,1,1},{-1,1,1}};const int f[36]={0,1,2,0,2,3,4,5,6,4,6,7,0,4,7,0,7,1,3,2,6,3,6,5,1,7,6,1,6,2,0,3,5,0,5,4};std::vector<V>v;v.reserve(36);for(int i=0;i<36;i++){auto q=p[f[i]];v.push_back({q,XMFLOAT3{q.x,q.y,q.z}});}return v;}
bool Graphics::initialize(HWND hwnd,int width,int height,bool vsync){hwnd_=hwnd;width_=std::max(1,width);height_=std::max(1,height);vsync_=vsync;DXGI_SWAP_CHAIN_DESC sd{};sd.BufferCount=2;sd.BufferDesc.Width=width_;sd.BufferDesc.Height=height_;sd.BufferDesc.Format=DXGI_FORMAT_R8G8B8A8_UNORM;sd.BufferUsage=DXGI_USAGE_RENDER_TARGET_OUTPUT;sd.OutputWindow=hwnd_;sd.SampleDesc.Count=1;sd.Windowed=TRUE;sd.SwapEffect=DXGI_SWAP_EFFECT_FLIP_DISCARD;D3D_FEATURE_LEVEL fl;HRESULT hr=D3D11CreateDeviceAndSwapChain(nullptr,D3D_DRIVER_TYPE_HARDWARE,nullptr,0,nullptr,0,D3D11_SDK_VERSION,&sd,&swap_,&device_,&fl,&context_);return SUCCEEDED(hr)&&makeShaders()&&makeBuffers();}
bool Graphics::makeShaders(){ComPtr<ID3DBlob>v,p,e;HRESULT h=D3DCompile(HLSL,strlen(HLSL),"tiny",nullptr,nullptr,"VS","vs_5_0",0,0,&v,&e);if(FAILED(h))return false;h=D3DCompile(HLSL,strlen(HLSL),"tiny",nullptr,nullptr,"PS","ps_5_0",0,0,&p,&e);if(FAILED(h))return false;if(FAILED(device_->CreateVertexShader(v->GetBufferPointer(),v->GetBufferSize(),nullptr,&vs_)))return false;if(FAILED(device_->CreatePixelShader(p->GetBufferPointer(),p->GetBufferSize(),nullptr,&ps_)))return false;D3D11_INPUT_ELEMENT_DESC d[]={{"POSITION",0,DXGI_FORMAT_R32G32B32_FLOAT,0,0,D3D11_INPUT_PER_VERTEX_DATA,0},{"NORMAL",0,DXGI_FORMAT_R32G32B32_FLOAT,0,12,D3D11_INPUT_PER_VERTEX_DATA,0}};return SUCCEEDED(device_->CreateInputLayout(d,2,v->GetBufferPointer(),v->GetBufferSize(),&layout_));}
bool Graphics::makeBuffers(){auto v=cubeVerts();D3D11_BUFFER_DESC bd{};bd.ByteWidth=UINT(v.size()*sizeof(V));bd.Usage=D3D11_USAGE_DEFAULT;bd.BindFlags=D3D11_BIND_VERTEX_BUFFER;D3D11_SUBRESOURCE_DATA init{v.data(),0,0};if(FAILED(device_->CreateBuffer(&bd,&init,&vb_)))return false;bd.ByteWidth=sizeof(CBuf);bd.BindFlags=D3D11_BIND_CONSTANT_BUFFER;return SUCCEEDED(device_->CreateBuffer(&bd,nullptr,&cb_));}
void Graphics::resize(int w,int h){if(!swap_)return;context_->OMSetRenderTargets(0,nullptr,nullptr);rtv_.Reset();dsv_.Reset();depth_.Reset();width_=std::max(1,w);height_=std::max(1,h);if(FAILED(swap_->ResizeBuffers(0,width_,height_,DXGI_FORMAT_UNKNOWN,0)))return;ComPtr<ID3D11Texture2D>b;if(SUCCEEDED(swap_->GetBuffer(0,IID_PPV_ARGS(&b))))device_->CreateRenderTargetView(b.Get(),nullptr,&rtv_);D3D11_TEXTURE2D_DESC dd{};dd.Width=width_;dd.Height=height_;dd.MipLevels=1;dd.ArraySize=1;dd.Format=DXGI_FORMAT_D24_UNORM_S8_UINT;dd.SampleDesc.Count=1;dd.BindFlags=D3D11_BIND_DEPTH_STENCIL;if(SUCCEEDED(device_->CreateTexture2D(&dd,nullptr,&depth_)))device_->CreateDepthStencilView(depth_.Get(),nullptr,&dsv_);}
void Graphics::beginFrame(const float c[4]){if(!rtv_)resize(width_,height_);context_->OMSetRenderTargets(1,rtv_.GetAddressOf(),dsv_.Get());context_->ClearRenderTargetView(rtv_.Get(),c);context_->ClearDepthStencilView(dsv_.Get(),D3D11_CLEAR_DEPTH|D3D11_CLEAR_STENCIL,1,0);D3D11_VIEWPORT vp{0,0,float(width_),float(height_),0,1};context_->RSSetViewports(1,&vp);}
void Graphics::drawEntity(const Entity&e,const XMMATRIX&view,const XMMATRIX&proj,const XMMATRIX&){if(e.kind==EntityKind::Camera||e.kind==EntityKind::DirectionalLight||e.kind==EntityKind::PointLight||e.kind==EntityKind::SpotLight)return;XMMATRIX model=XMMatrixScaling(e.transform.scale.x,e.transform.scale.y,e.transform.scale.z)*XMMatrixRotationRollPitchYaw(XMConvertToRadians(e.transform.rotation.x),XMConvertToRadians(e.transform.rotation.y),XMConvertToRadians(e.transform.rotation.z))*XMMatrixTranslation(e.transform.position.x,e.transform.position.y,e.transform.position.z);CBuf c{};XMStoreFloat4x4(&c.model,XMMatrixTranspose(model));XMStoreFloat4x4(&c.mvp,XMMatrixTranspose(model*view*proj));c.base=e.material.color;c.lightDir=XMFLOAT4(-.45f,-.9f,-.3f,0);c.lightColor=XMFLOAT4(1,1,1,1.2f);c.camera=XMFLOAT4(0,2,-8,1);UINT stride=sizeof(V),off=0;context_->UpdateSubresource(cb_.Get(),0,nullptr,&c,0,0);context_->IASetVertexBuffers(0,1,vb_.GetAddressOf(),&stride,&off);context_->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST);context_->IASetInputLayout(layout_.Get());context_->VSSetShader(vs_.Get(),nullptr,0);context_->PSSetShader(ps_.Get(),nullptr,0);context_->VSSetConstantBuffers(0,1,cb_.GetAddressOf());context_->PSSetConstantBuffers(0,1,cb_.GetAddressOf());context_->Draw(36,0);}
void Graphics::drawScene(const Scene&sc,const XMMATRIX&view,const XMMATRIX&proj){for(const auto&e:sc.entities)if(e.visible)drawEntity(e,view,proj,{});}void Graphics::endFrame(){if(swap_)swap_->Present(vsync_?1:0,0);}
void Engine::initialize(HWND hwnd,int w,int h){gfx_.initialize(hwnd,w,h,true);scene_.entities.clear();scene_.nextId=1;Entity cam;cam.id=scene_.nextId++;cam.name="Main Camera";cam.kind=EntityKind::Camera;cam.transform.position={0,2,-8};scene_.cameraId=cam.id;scene_.entities.push_back(cam);Entity light;light.id=scene_.nextId++;light.name="Sun";light.kind=EntityKind::DirectionalLight;light.transform.rotation={35,-35,0};scene_.entities.push_back(light);Entity ground;ground.id=scene_.nextId++;ground.name="Ground";ground.kind=EntityKind::Plane;ground.transform.scale={6,.1f,6};ground.material.color={.3f,.34f,.38f,1};scene_.entities.push_back(ground);Entity cube;cube.id=scene_.nextId++;cube.name="Player";cube.kind=EntityKind::Cube;cube.transform.position={0,1,0};cube.dynamic=true;scene_.entities.push_back(cube);}
void Engine::resize(int w,int h){gfx_.resize(w,h);}void Engine::play(bool v){playing_=v;if(!v)time_=0;}void Engine::tick(float dt){if(playing_)simulate(dt);}void Engine::simulate(float dt){for(auto&e:scene_.entities)if(e.dynamic){float x=0,z=0;if(keyDown('W'))z+=1;if(keyDown('S'))z-=1;if(keyDown('A'))x-=1;if(keyDown('D'))x+=1;float l=std::sqrt(x*x+z*z);if(l>0){x/=l;z/=l;e.transform.position.x+=x*5*dt;e.transform.position.z+=z*5*dt;}}}
XMMATRIX Engine::cameraView()const{auto it=std::find_if(scene_.entities.begin(),scene_.entities.end(),[&](const auto&e){return e.id==scene_.cameraId;});XMFLOAT3 p=it==scene_.entities.end()?XMFLOAT3{0,2,-8}:it->transform.position;return XMMatrixLookAtLH(XMLoadFloat3(&p),XMVectorSet(p.x,p.y,p.z+1,1),XMVectorSet(0,1,0,0));}XMMATRIX Engine::cameraProjection()const{return XMMatrixPerspectiveFovLH(XMConvertToRadians(60),float(16)/9,.1f,1000);}
void Engine::render(){float c[]={.045f,.055f,.075f,1};gfx_.beginFrame(c);gfx_.drawScene(scene_,cameraView(),cameraProjection());gfx_.endFrame();}
}
