#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <windowsx.h>
#include <fstream>
#include <string>
#include <vector>
#include <cmath>
#include <algorithm>

struct Obj { std::string name; int type=0; float x=0,y=0,z=0,rx=0,ry=0,rz=0,sx=1,sy=1,sz=1; int color=0; };
static std::vector<Obj> scene; static float camX=0,camY=1.5f,camZ=-10.f,camYaw=0,camPitch=0; static float lastT=0;
static bool quoted(std::istream&in,std::string&out){in>>std::ws;if(in.peek()!='"'){in>>out;return bool(in);}in.get();std::getline(in,out,'"');return bool(in);}
static bool load(const char*path){std::ifstream f(path);if(!f)return false;std::string header;f>>header;scene.clear();std::string t;while(f>>t){if(t!="object")break;Obj o;if(header=="TinyAI"?quoted(f,o.name):bool(f>>o.name)){if(header=="TinyAI"){f>>o.type>>o.x>>o.y>>o.z>>o.rx>>o.ry>>o.rz>>o.sx>>o.sy>>o.sz>>o.color;}else{f>>o.x>>o.y>>o.z>>o.rx>>o.ry>>o.rz>>o.sx;o.sy=o.sz=o.sx;}if(f)scene.push_back(o);}}return !scene.empty();}
static POINT P(float x,float y,float z,RECT&r){float cy=cosf(camYaw),sy=sinf(camYaw),cp=cosf(camPitch),sp=sinf(camPitch);float X=x-camX,Y=y-camY,Z=z-camZ;float xx=X*cy-Z*sy,zz=X*sy+Z*cy;float yy=Y*cp-zz*sp,zz2=Y*sp+zz*cp;zz2=std::max(0.2f,zz2);float f=0.9f;return{(LONG)(r.right/2+xx*f*r.bottom/zz2),(LONG)(r.bottom/2-yy*f*r.bottom/zz2)};}
static void cube(HDC dc,const Obj&o,RECT&r){float rx=o.rx*.0174533f,ry=o.ry*.0174533f,rz=o.rz*.0174533f;float v[8][3]={{-1,-1,-1},{1,-1,-1},{1,1,-1},{-1,1,-1},{-1,-1,1},{1,-1,1},{1,1,1},{-1,1,1}};POINT p[8];for(int i=0;i<8;i++){float x=v[i][0]*o.sx,y=v[i][1]*o.sy,z=v[i][2]*o.sz;float cx=cosf(rx),sx=sinf(rx),cy=cosf(ry),sy=sinf(ry),cz=cosf(rz),sz=sinf(rz);float y1=y*cx-z*sx,z1=y*sx+z*cx;float x2=x*cy-z1*sy,z2=x*sy+z1*cy;float x3=x2*cz-y1*sz,y3=x2*sz+y1*cz;p[i]=P(x3+o.x,y3+o.y,z2+o.z,r);}int e[][2]={{0,1},{1,2},{2,3},{3,0},{4,5},{5,6},{6,7},{7,4},{0,4},{1,5},{2,6},{3,7}};HPEN pen=CreatePen(PS_SOLID,2,RGB(90,190,245));HGDIOBJ old=SelectObject(dc,pen);for(auto&q:e){MoveToEx(dc,p[q[0]].x,p[q[0]].y,nullptr);LineTo(dc,p[q[1]].x,p[q[1]].y);}SelectObject(dc,old);DeleteObject(pen);}
static LRESULT CALLBACK W(HWND h,UINT m,WPARAM w,LPARAM l){if(m==WM_PAINT){PAINTSTRUCT ps;HDC dc=BeginPaint(h,&ps);RECT r;GetClientRect(h,&r);FillRect(dc,&r,(HBRUSH)GetStockObject(BLACK_BRUSH));for(auto&o:scene)if(o.name!="Main Camera")cube(dc,o,r);SetBkMode(dc,TRANSPARENT);SetTextColor(dc,RGB(210,215,225));TextOutA(dc,16,14,"Tiny AI Game",12);TextOutA(dc,16,36,"WASD move  |  RMB look  |  Esc quit",35);EndPaint(h,&ps);return 0;}if(m==WM_MOUSEMOVE&&GetAsyncKeyState(VK_RBUTTON)&0x8000){static POINT last={GET_X_LPARAM(l),GET_Y_LPARAM(l)};int dx=GET_X_LPARAM(l)-last.x,dy=GET_Y_LPARAM(l)-last.y;camYaw+=dx*.004f;camPitch=std::clamp(camPitch+dy*.004f,-1.4f,1.4f);last={GET_X_LPARAM(l),GET_Y_LPARAM(l)};InvalidateRect(h,nullptr,FALSE);return 0;}if(m==WM_RBUTTONDOWN){SetCapture(h);return 0;}if(m==WM_RBUTTONUP){ReleaseCapture();return 0;}if(m==WM_KEYDOWN&&w==VK_ESCAPE){DestroyWindow(h);return 0;}if(m==WM_TIMER){float dt=.016f;float s=5.f*dt;float sy=sinf(camYaw),cy=cosf(camYaw);if(GetAsyncKeyState('W')&0x8000){camX+=sy*s;camZ+=cy*s;}if(GetAsyncKeyState('S')&0x8000){camX-=sy*s;camZ-=cy*s;}if(GetAsyncKeyState('A')&0x8000){camX-=cy*s;camZ+=sy*s;}if(GetAsyncKeyState('D')&0x8000){camX+=cy*s;camZ-=sy*s;}InvalidateRect(h,nullptr,FALSE);}if(m==WM_DESTROY)PostQuitMessage(0);return DefWindowProcA(h,m,w,l);}
int WINAPI WinMain(HINSTANCE hi,HINSTANCE,LPSTR cmd,int){const char*path=(cmd&&*cmd)?cmd:"project.tinyproj";while(*path==' '||*path=='"')++path;std::string p(path);if(!p.empty()&&p.back()=='"')p.pop_back();if(!load(p.c_str()))scene.push_back({"Cube",0,0,0,0,0,0,1,1,1,0});WNDCLASSA c{};c.hInstance=hi;c.lpfnWndProc=W;c.lpszClassName="TinyAIRuntime";c.hCursor=LoadCursor(nullptr,IDC_ARROW);RegisterClassA(&c);HWND w=CreateWindowA(c.lpszClassName,"Tiny AI Game",WS_OVERLAPPEDWINDOW|WS_VISIBLE,180,90,1100,700,nullptr,nullptr,hi,nullptr);SetTimer(w,1,16,nullptr);MSG m{};while(GetMessageA(&m,nullptr,0,0)){TranslateMessage(&m);DispatchMessageA(&m);}return 0;}
