#include "script.hpp"
#include <cctype>
#include <cstdlib>
#include <sstream>
namespace tiny::script {
namespace {struct Tok{std::string s;int line;};std::vector<Tok> tokens(const std::string&line,int n){std::vector<Tok>r;for(size_t i=0;i<line.size();){if(std::isspace((unsigned char)line[i])){++i;continue;}if(line[i]=='"'){size_t j=++i;while(j<line.size()&&line[j]!='"')++j;if(j>=line.size())return{{"<error>",n}};r.push_back({"\""+line.substr(i,j-i)+"\"",n});i=j+1;continue;}size_t j=i;while(j<line.size()&&!std::isspace((unsigned char)line[j]))++j;r.push_back({line.substr(i,j-i),n});i=j;}return r;}bool number(const std::string&s,double&v){char*e=nullptr;v=std::strtod(s.c_str(),&e);return e&&*e==0;}}
CompileResult compile(const std::string&src){CompileResult r;std::istringstream in(src);std::string line;int ln=0;bool event=false;while(std::getline(in,line)){++ln;auto first=line.find_first_not_of(" \t");if(first==std::string::npos)continue;if(first==0&&line.back()==':'){std::string name=line.substr(0,line.size()-1);if(name!="start"&&name!="update")r.errors.push_back({ln,"Unknown event. Use start: or update:."});event=true;continue;}if(!event){r.errors.push_back({ln,"Statements must be inside start: or update:."});continue;}auto t=tokens(line,ln);if(t.size()==1&&t[0].s=="<error>"){r.errors.push_back({ln,"Unterminated string."});continue;}if(t[0].s=="say"){if(t.size()!=2||t[1].s.size()<2||t[1].s.front()!='"'||t[1].s.back()!='"')r.errors.push_back({ln,"say expects quoted text."});else{r.program.code.push_back({Op::PushString,0,t[1].s.substr(1,t[1].s.size()-2),0});r.program.code.push_back({Op::Native,0,"say",1});}continue;}if(t[0].s=="move"||t[0].s=="rotate"){if(t.size()!=4){r.errors.push_back({ln,t[0].s+" expects three values."});continue;}for(size_t k=1;k<4;k++){double v;if(number(t[k].s,v))r.program.code.push_back({Op::PushNumber,v,"",0});else if(t[k].s=="time")r.program.code.push_back({Op::Native,0,"time",0});else r.errors.push_back({ln,"Expected a number or time."});}r.program.code.push_back({Op::Native,0,t[0].s,3});continue;}if(t[0].s=="destroy"||t[0].s=="spawn"){if(t.size()!=1&&t.size()!=2){r.errors.push_back({ln,t[0].s+" expects an optional name."});continue;}if(t.size()==2)r.program.code.push_back({Op::PushString,0,t[1].s,0});r.program.code.push_back({Op::Native,0,t[0].s,(int)t.size()-1});continue;}if(t.size()>=3&&t[1].s=="="){double v;if(number(t[2].s,v))r.program.code.push_back({Op::PushNumber,v,"",0});else if(t[2].s=="true"||t[2].s=="false")r.program.code.push_back({Op::PushBool,t[2].s=="true","",0});else{r.errors.push_back({ln,"Assignment expects a number or boolean in this release."});continue;}r.program.variables.push_back(t[0].s);r.program.code.push_back({Op::Store,0,t[0].s,0});continue;}r.errors.push_back({ln,"Unknown statement '"+t[0].s+"'."});}r.program.code.push_back({Op::Halt});return r;}
bool VM::run(const Program&p,int budget){stack_.clear();vars_.clear();size_t pc=0;for(int steps=0;pc<p.code.size()&&steps<budget;++steps){const auto&i=p.code[pc++];switch(i.op){case Op::PushNumber:stack_.push_back(std::to_string(i.number));break;case Op::PushString:stack_.push_back(i.text);break;case Op::PushBool:stack_.push_back(i.number?"true":"false");break;case Op::Store:if(stack_.empty())return false;vars_[i.text]=std::strtod(stack_.back().c_str(),nullptr);stack_.pop_back();break;case Op::Native:{std::vector<std::string>a;for(int n=0;n<i.arg;n++){if(stack_.empty())return false;a.push_back(stack_.back());stack_.pop_back();}if(native_)native_(i.text,a);break;}case Op::Halt:return true;default:break;}}return false;}
}
