#include "script.hpp"
#include <algorithm>
#include <cctype>
#include <sstream>
#include <unordered_map>
#include <functional>
#include <variant>
namespace tiny::script {
namespace {struct Tok{std::string s;int line;};std::vector<Tok> lineTokens(const std::string&line,int n){std::vector<Tok>r;for(size_t i=0;i<line.size();){if(std::isspace((unsigned char)line[i])){++i;continue;}if(line[i]=='"'){size_t j=++i;while(j<line.size()&&line[j]!='"')++j;r.push_back({"\""+line.substr(i,j-i)+"\"",n});i=j+(j<line.size());continue;}size_t j=i;while(j<line.size()&&!std::isspace((unsigned char)line[j]))++j;r.push_back({line.substr(i,j-i),n});i=j;}return r;}
bool num(const std::string&s,double&v){char*e=nullptr;v=strtod(s.c_str(),&e);return e&&*e==0;}}
CompileResult compile(const std::string&src){CompileResult r;std::istringstream in(src);std::string line;int ln=0;bool event=false;while(std::getline(in,line)){++ln;if(line.find_first_not_of(" \t\r")==std::string::npos)continue;if(line.find_first_not_of(" \t")==0&&line.back()==':'){auto name=line.substr(0,line.size()-1);if(name!="start"&&name!="update"&&name!="ready"){r.errors.push_back({ln,"Unknown event '"+name+"'. Use start: or update:."});}event=true;continue;}if(!event){r.errors.push_back({ln,"Put gameplay statements under start: or update:."});continue;}auto t=lineTokens(line,ln);if(t.empty())continue;if(t[0].s=="say"){if(t.size()!=2||t[1].s.size()<2||t[1].s.front()!='"'||t[1].s.back()!='"')r.errors.push_back({ln,"say expects quoted text."});else r.program.code.push_back({Op::PushString,0,t[1].s.substr(1,t[1].s.size()-2),0}),r.program.code.push_back({Op::Native,0,"say",1});continue;}if(t[0].s=="move"||t[0].s=="rotate"||t[0].s=="destroy"||t[0].s=="spawn"){r.program.code.push_back({Op::Native,0,t[0].s,(int)t.size()-1});for(size_t i=1;i<t.size();++i){double v;if(num(t[i].s,v))r.program.code.push_back({Op::PushNumber,v,"",0});else if(t[i].s=="time")r.program.code.push_back({Op::Native,0,"time",0});else r.errors.push_back({ln,"Expected a number or time in '"+t[0].s+"'."});}continue;}if(t.size()>=3&&t[1].s=="="){double v;if(num(t[2].s,v)){r.program.code.push_back({Op::PushNumber,v,"",0});r.program.variables.push_back(t[0].s);r.program.code.push_back({Op::Store,0,t[0].s,0});}else if(t[2].s=="true"||t[2].s=="false"){r.program.code.push_back({Op::PushBool,t[2].s=="true","",0});r.program.variables.push_back(t[0].s);r.program.code.push_back({Op::Store,0,t[0].s,0});}else r.errors.push_back({ln,"Assignment expects a number or boolean."});continue;}r.errors.push_back({ln,"Unknown statement '"+t[0].s+"'."});}r.program.code.push_back({Op::Halt});return r;}
bool VM::run(const Program&p,int budget){reset();int steps=0;while(pc_<p.code.size()&&!halted_&&steps++<budget){auto&i=p.code[pc_++];switch(i.op){case Op::PushNumber:stack_.push_back(std::to_string(i.number));break;case Op::PushString:stack_.push_back(i.text);break;case Op::PushBool:stack_.push_back(i.number?"true":"false");break;case Op::Store:if(stack_.empty())return false;vars_[i.text]=strtod(stack_.back().c_str(),nullptr);stack_.pop_back();break;case Op::Native:{std::vector<std::string>a;for(int n=0;n<i.arg&&!stack_.empty();++n){a.push_back(stack_.back());stack_.pop_back());}if(native_)native_(i.text,a);break;}case Op::Halt:halted_=true;break;default:break;}}return halted_||steps<budget;}
}
